name: Build/release

on:
  workflow_dispatch:
  pull_request:

jobs:
  linux:
    name: Release on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Download dependencies
        run: npm install

      - name: Release Linux
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: npm run pack:linux

      - name: Linux Release App Image
        uses: actions/upload-artifact@v1
        with:
          name: CadekCompanyManagementv2.AppImage
          path: dist/CadekCompanyManagementv2.AppImage

      - name: Linux Release deb package
        uses: actions/upload-artifact@v1
        with:
          name: CadekCompanyManagementv2.deb
          path: dist/CadekCompanyManagementv2.deb