name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Download dependencies
        run: npm install

      - name: Release Mac
        if: startsWith(matrix.os, 'macos')
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: electron-builder --mac

      - name: Release Linux
        if: startsWith(matrix.os,'ubuntu')
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: electron-builder --linux

      - name: Release Windows
        if: startsWith(matrix.os,'windows')
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: electron-builder --windows