name: Build/release

on: push

jobs:
  linux:
    name: Release on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Download dependencies
        run: npm install

      - name: Release Linux
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: npm run pack:linux

      - name: Linux Release App Image
        uses: actions/upload-artifact@v1
        with:
          name: CadekCompanyManagementv2.AppImage
          path: dist/CadekCompanyManagementv2.AppImage

      - name: Linux Release deb package
        uses: actions/upload-artifact@v1
        with:
          name: CadekCompanyManagementv2.deb
          path: dist/CadekCompanyManagementv2.deb


  windows:
    name: Release on Windows
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Download dependencies
        run: npm install

      - name: Release Windows
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: npm run pack:win

      - name: Windows Release Setup.exe
        uses: actions/upload-artifact@v1
        with:
          name: CadekCompanyManagementv2.exe
          path: dist/CadekCompanyManagementv2.exe


  mac:
    name: Release on Mac
    runs-on: macos-latest
    needs: [windows, linux]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Download dependencies
        run: npm install

      - name: Release Mac
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: npm run pack:mac

      - name: Mac Release dmg
        uses: actions/upload-artifact@v1
        with:
          name: CadekCompanyManagementv2.dmg
          path: dist/CadekCompanyManagementv2.dmg